import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { openSans } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <main className=" min-h-svh bg-gradient-to-b overflow-hidden">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
